import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Navigation from "@/components/Navigation";
import { pages } from "@/data/routes";
import { Oswald } from "next/font/google";

const oswald = Oswald({subsets: ["latin"]})


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <Navigation links={pages}/>
        <div className={`mainContent ${oswald.className}`}>
        {children}
        </div>
      </body>
    </html>
  );
}
